name = "SatSolver"
uuid = "19162200-215e-47cb-8549-eaa9b939e44b"
authors = ["alessandro alessandrostr95@gmail.com"]
version = "0.1.0"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
PrettyTables = "^1.2.2"
julia = "1"
